"use client";

import {useEffect,useState} from "react";

type FieldProps={id:string;label:string;rows?:number};
function useStored(id:string){const[v,setV]=useState("");useEffect(()=>setV(localStorage.getItem(`mars-book-${id}`)||""),[id]);useEffect(()=>{const t=setTimeout(()=>localStorage.setItem(`mars-book-${id}`,v),180);return()=>clearTimeout(t)},[id,v]);return[v,setV] as const}
function Field({id,label,rows=3}:FieldProps){const[v,setV]=useStored(id);return <label className="field"><b>{label}</b><textarea rows={rows} value={v} onChange={e=>setV(e.target.value)}/></label>}
function Checks({id,items}:{id:string;items:string[]}){const[v,setV]=useStored(id),a=v?v.split("||"):[];return <div className="checks">{items.map(x=><label key={x}><input type="checkbox" checked={a.includes(x)} onChange={()=>setV(a.includes(x)?a.filter(y=>y!==x).join("||"):[...a,x].join("||"))}/><span>{x}</span></label>)}</div>}
function Note({text}:{text:string}){return <aside className="compactNote"><p>{text}</p></aside>}
function Pages({n,left,right}:{n:number;left:React.ReactNode;right:React.ReactNode}){return <><article className="page left"><div className="num">{String(n).padStart(2,"0")}</div>{left}</article><article className="page right">{right}</article></>}

function Spread28(){return <Pages n={28} left={<><p className="eyebrow">ШТАБ-КВАРТИРА. ПЛАНИРОВАНИЕ РЕАЛИЗАЦИИ</p><h1>Свободное пространство «Мои заметки и расчёты»</h1><Note text="Для конкретных вычислений, скетчей макетов, текстов для соцсетей, списка тем для обсуждения с экспертами."/><Field id="p28-notes-left" label="Мои заметки и расчёты" rows={28}/></>} right={<><h1>Продолжение заметок</h1><Field id="p28-notes-right" label="Свободное пространство" rows={34}/></>}/>}

function Spread29(){return <Pages n={29} left={<><p className="eyebrow">МОЯ ПРОЕКТНАЯ ВСЕЛЕННАЯ</p><h1>Проекты, которые зажигают меня</h1><p>Вспомни моменты, когда тебе было интересно, весело, важно или очень хотелось, чтобы получилось.</p><h2>Мои яркие проекты:</h2><Field id="p29-project1" label="1." rows={3}/><Field id="p29-project2" label="2." rows={3}/><Field id="p29-project3" label="3." rows={3}/><Field id="p29-project4" label="4." rows={3}/><Field id="p29-project5" label="5." rows={3}/><Field id="p29-most-mine" label="👩‍💻 Проект, который был самым «моим»:" rows={5}/><h2>Мои роли — кем я был(а) в проектах?</h2><Checks id="p29-roles" items={["Исследователь","Придумыватель идей","Помощник в команде","Организатор маленького процесса","Дизайнер решений","Интервьюер","Создатель прототипа","Человек, который вдохновлял других","Другая роль"]}/><Field id="p29-role-other" label="Другими словами, я был(а)" rows={4}/><Field id="p29-best-role" label="👑 Роль, в которой мне было особенно классно:" rows={4}/></>} right={<><h1>Что я пробовал(а) и как это сработало?</h1><p>(пилотирование)</p><Field id="p29-tested-where" label="🔥 Где я тестировал(а) свою идею:" rows={6}/><Field id="p29-tested-what" label="🧪 Что мы проверяли:" rows={6}/><Field id="p29-reaction" label="🎯 Как люди реагировали:" rows={6}/><Field id="p29-best-pilot" label="👉 Самый классный момент пилота:" rows={6}/><h2>Результат, который случился благодаря мне</h2><Field id="p29-result1" label="1." rows={4}/><Field id="p29-result2" label="2." rows={4}/><Field id="p29-result3" label="3." rows={4}/><Field id="p29-proud" label="✨ Результат, которым я особенно горжусь:" rows={7}/></>}/>}

function Spread30(){return <Pages n={30} left={<><p className="eyebrow">МОЯ ПРОЕКТНАЯ ВСЕЛЕННАЯ</p><h1>Где про мой проект говорили?</h1><p>(чтобы увидеть, какой я уже крутой(ая) и что я создавал(а))</p><Checks id="p30-media" items={["Пост в школьном чате","Пост на сайте МАРС","Фото/видео на событии","Рассказывали кураторы","Показали на МАРСФЕСТе","Публикация в соцсетях","Другое"]}/><Field id="p30-links" label="👉 Ссылки или фото:" rows={18}/></>} right={<><h1>Что этот проект говорит обо мне?</h1><Field id="p30-can" label="Я могу…" rows={9}/><Field id="p30-skill" label="• Я умею…" rows={8}/><Field id="p30-interest" label="• Мне интересно…" rows={8}/><Field id="p30-cv" label="🪪 Одна фраза, которую я положу в своё резюме:" rows={8}/><Field id="p30-notes" label="Заметки" rows={10}/></>}/>}

const spreads=[Spread28,Spread29,Spread30];
export default function BookNext6(){const[page,setPage]=useState(28);useEffect(()=>{const raw=Number(new URLSearchParams(location.search).get("page")||28);setPage(Math.min(30,Math.max(28,raw)))},[]);useEffect(()=>{const p=new URLSearchParams(location.search);p.set("page",String(page));history.replaceState(null,"",`${location.pathname}?${p.toString()}`);localStorage.setItem("mars-book-current-page",String(page));window.scrollTo({top:0,behavior:"smooth"})},[page]);const Spread=spreads[page-28];return <main><header><div className="brand"><img src="/mars-logo.svg" alt="МАРС"/><div><b>Живая планёрка</b><span>Личный кабинет</span></div></div><div className="meta"><span>Разворот {page} из 38</span><span>Сохранено ✓</span></div><a href="/student">← К моему маршруту</a></header><section className="frame"><div className="spread"><Spread/></div></section><footer><a className="button" href={page===28?"/book-next5?page=27&mode=student":`/book-next6?page=${page-1}&mode=student`}>← Предыдущий</a><span>{page} / 38</span><button disabled={page===30} onClick={()=>setPage(p=>Math.min(30,p+1))}>Следующий →</button></footer><style jsx global>{`
*{box-sizing:border-box}html,body{margin:0;background:#e9e5ed;color:#2b2432;font-family:Inter,Arial,sans-serif}main{min-height:100vh;padding-bottom:24px}header{height:72px;display:flex;align-items:center;gap:22px;padding:0 28px;background:#fff;border-bottom:1px solid #ded7e4;position:sticky;top:0;z-index:20}.brand{display:flex;align-items:center;gap:12px}.brand img{width:72px}.brand div{display:grid}.brand b{color:#5220a8}.brand span{font-size:12px;color:#8a8191}.meta{margin-left:auto;display:flex;gap:8px}.meta span{padding:8px 11px;border-radius:999px;background:#f1ecf7;color:#6130b5;font-size:13px;font-weight:800}.meta span:last-child{background:#ebf6ee;color:#35734b}header a{color:#5220a8;text-decoration:none;font-weight:800;font-size:13px}.frame{padding:18px 22px 10px}.spread{max-width:1420px;margin:auto;display:grid;grid-template-columns:1fr 1fr;filter:drop-shadow(0 24px 40px #2d203b28)}.page{min-height:850px;background:#fffdf8;padding:28px 32px 24px;position:relative;overflow:hidden}.left{border-radius:18px 0 0 18px;border-right:1px solid #ddd4e2}.right{border-radius:0 18px 18px 0;border-left:1px solid #efe9f2}.num{position:absolute;right:30px;top:22px;font:800 42px Georgia;color:#f05b37}.eyebrow{margin:0 0 7px;color:#7444c6;font-size:10px;font-weight:900;letter-spacing:.11em}.page h1{margin:0 0 10px;font:800 34px/1.08 Georgia;max-width:84%}.page h2{margin:13px 0 8px;font:800 21px Georgia}.page p{line-height:1.45}.field{display:grid;gap:6px;border:1px solid #cfc5bb;padding:8px 9px 6px;margin:7px 0;background:#fffefb}.field b{font:700 14px Georgia}.field textarea{width:100%;border:0;outline:0;resize:vertical;font:13px/1.6 Inter;background:repeating-linear-gradient(to bottom,transparent 0,transparent 23px,#ddd7cf 24px);min-height:46px;color:#2a2233}.compactNote{padding:7px 10px;border:1px solid #e2bc55;border-radius:6px;margin:8px 0;font-size:12px;line-height:1.35;display:block;width:fit-content;max-width:min(100%,620px);height:auto;background:#fff7df}.compactNote p{margin:0}.checks{display:grid;gap:6px}.checks label{display:flex;gap:8px;align-items:flex-start;padding:7px 8px;border:1px solid #ddd5cd;border-radius:8px;background:#fff;font-size:13px;line-height:1.35}footer{max-width:1420px;margin:12px auto 0;padding:0 22px;display:flex;justify-content:space-between;align-items:center}footer button,.button{border:0;border-radius:12px;padding:11px 15px;background:#5b27b1;color:#fff;font-weight:800;text-decoration:none}footer button:disabled{opacity:.35}footer span{font-weight:900;color:#5b27b1}@media(max-width:980px){header{padding:0 16px}.brand div,.meta{display:none}.frame{padding:12px}.spread{grid-template-columns:1fr}.page{min-height:auto;border-radius:14px!important;border:0!important}.right{margin-top:12px}}@media(max-width:650px){header{height:62px}.page{padding:22px 16px}.page h1{font-size:29px}footer button,.button{font-size:12px;padding:9px 10px}}
`}</style></main>}
