"use client";

import {useEffect,useState} from "react";

type FieldProps={id:string;label:string;rows?:number};
function useStored(id:string){const[v,setV]=useState("");useEffect(()=>setV(localStorage.getItem(`mars-book-${id}`)||""),[id]);useEffect(()=>{const t=setTimeout(()=>localStorage.setItem(`mars-book-${id}`,v),180);return()=>clearTimeout(t)},[id,v]);return[v,setV] as const}
function Field({id,label,rows=3}:FieldProps){const[v,setV]=useStored(id);return <label className="field"><b>{label}</b><textarea rows={rows} value={v} onChange={e=>setV(e.target.value)}/></label>}
function Checks({id,items}:{id:string;items:string[]}){const[v,setV]=useStored(id),a=v?v.split("||"):[];return <div className="checks">{items.map(x=><label key={x}><input type="checkbox" checked={a.includes(x)} onChange={()=>setV(a.includes(x)?a.filter(y=>y!==x).join("||"):[...a,x].join("||"))}/><span>{x}</span></label>)}</div>}
function Choice({id,items}:{id:string;items:string[]}){const[v,setV]=useStored(id);return <div className="choices">{items.map(x=><label key={x} className={v===x?"sel":""}><input type="radio" name={id} checked={v===x} onChange={()=>setV(x)}/><span>{x}</span></label>)}</div>}
function Pages({n,left,right}:{n:number;left:React.ReactNode;right:React.ReactNode}){return <><article className="page left"><div className="num">{String(n).padStart(2,"0")}</div>{left}</article><article className="page right">{right}</article></>}

function Spread37(){return <Pages n={37} left={<><p className="eyebrow">ПУТЕШЕСТВИЕ И НАСТРОЙКА НА ИГРУ</p><h1>Моё путешествие в Великий Новгород</h1><h2>1. Моя интенция поездки</h2><p>Зачем я еду? Что хочу почувствовать, узнать, прожить?</p><Field id="p37-intention" label="Мой ответ:" rows={5}/><h2>2. Каким я хочу быть в этом путешествии</h2><p>Выбери 3 качества, которые зададут тон поездке:</p><Checks id="p37-qualities" items={["внимательный","лёгкий","открытый","наблюдательный","смелый","дружелюбный","исследователь","игрок","создатель атмосферы"]}/><Field id="p37-own-qualities" label="Мои качества:" rows={3}/><h2>3. Мой исследовательский ракурс</h2><p>Что я хочу изучать в Великом Новгороде? (архитектура, граффити, история торговли, жизнь маленького города, речь, лица, характеры)</p><Field id="p37-focus" label="Мой выбор:" rows={5}/><h2>4. Мой образ путешественника</h2><Choice id="p37-image" items={["хронист","искатель историй","коллекционер смыслов","наблюдатель","создатель настроений"]}/><Field id="p37-image-own" label="Мой образ:" rows={3}/><h2>5. Что хочу привезти (невещное)</h2><p>Чувство, фразу, мысль, историю, состояние.</p><Field id="p37-bring" label="Мой ответ:" rows={6}/></>} right={<><h1>Легенда города и дневник путешествия</h1><h2>6. Легенда города: что хочу увидеть лично</h2><p>Отметь важное:</p><Checks id="p37-places" items={["Детинец","Софийский собор","Ярославово Дворище","граффити","мост через Волхов","трактир","тихие улочки","музей деревянного зодчества"]}/><Field id="p37-place-list" label="Мой список:" rows={4}/><h2>7. Мой дневник путешествия</h2><p>Короткие заметки каждый день (фразой).</p>{[1,2,3,4,5,6].map(d=><Field key={d} id={`p37-day-${d}`} label={`День ${d}:`} rows={2}/>) }<h2>8. После поездки: мой итог</h2><Field id="p37-discovery" label="Что стало открытием?" rows={4}/><Field id="p37-belong" label="Когда почувствовал(а) себя частью места?" rows={4}/><Field id="p37-phrase" label="Какая мысль или фраза останется со мной?" rows={4}/></>}/>}

function Spread38(){return <Pages n={38} left={<><p className="eyebrow">ИГРА «УЕЗДНЫЙ ГОРОД N»</p><h1>Мой образ, характер и стратегия</h1><h2>1. Моя роль в игре</h2><p>Выбери или придумай:</p><Choice id="p38-role" items={["купец","чиновник","титулярный советник","помещик","офицер","священник","журналист","хозяйка салона","барышня","артистка","революционер","наблюдатель","образ из Гоголя, Пушкина или Достоевского","другая роль"]}/><Field id="p38-role-own" label="Моя роль:" rows={3}/><h2>2. Мой характер</h2><p>Отметь 5–7 черт:</p><Checks id="p38-character" items={["честолюбивый","хитрый","мягкий","элегантный","наблюдательный","романтичный","расчётливый","добродушный","артистичный","вспыльчивый","тихий"]}/><Field id="p38-character-own" label="Мой характер:" rows={4}/><h2>3. Моя легенда (краткая биография)</h2><p>Откуда я? Почему приехал(а)? Что ищу? Что скрываю?</p><Field id="p38-legend" label="Моя легенда:" rows={7}/><h2>4. Мои игровые цели</h2><p>Социальные, личные, эстетические, тайные. Чего хочу добиться? Какой эффект произвести? Что хочу понять о себе, играя в другого?</p><Field id="p38-goals" label="Мои цели:" rows={7}/><h2>5. Мой внешний образ</h2><p>Как держусь? Как говорю? Как смотрю? Как двигаюсь?</p><Field id="p38-appearance" label="Образ:" rows={5}/></>} right={<><h1>Отношения, ресурсы и запрос</h1><h2>6. Мои отношения в игре</h2><p>С кем мне нужно взаимодействовать? Кто союзник? Кто соперник? Кто источник смыслов?</p><Field id="p38-relations" label="Отношения:" rows={7}/><h2>7. Мои ресурсы и слабости персонажа</h2><p>Что я привношу? (интонация, юмор, мягкость, наблюдательность, умение объединять людей)</p><Field id="p38-resources" label="Мои ресурсы:" rows={6}/><Field id="p38-weaknesses" label="Слабости персонажа:" rows={5}/><h2>8. Мой эмоциональный запрос</h2><p>Что хочу прожить в игре?</p><Choice id="p38-emotion" items={["лёгкость","интригу","романтику","азарт","спокойствие","неожиданность","дружбу","наблюдение","другое"]}/><Field id="p38-emotion-own" label="Я выбираю:" rows={3}/><h2>9. Мой главный вопрос игры</h2><Field id="p38-question" label="Что я хочу понять о себе, проживая жизнь другого человека?" rows={9}/></>}/>}

const spreads=[Spread37,Spread38];
export default function BookNext9(){const[page,setPage]=useState(37);useEffect(()=>{const raw=Number(new URLSearchParams(location.search).get("page")||37);setPage(Math.min(38,Math.max(37,raw)))},[]);useEffect(()=>{const p=new URLSearchParams(location.search);p.set("page",String(page));history.replaceState(null,"",`${location.pathname}?${p.toString()}`);localStorage.setItem("mars-book-current-page",String(page));window.scrollTo({top:0,behavior:"smooth"})},[page]);const Spread=spreads[page-37];return <main><header><div className="brand"><img src="/mars-logo.svg" alt="МАРС"/><div><b>Живая планёрка</b><span>Личный кабинет</span></div></div><div className="meta"><span>Разворот {page} из 38</span><span>Сохранено ✓</span></div><a href="/student">← К моему маршруту</a></header><section className="frame"><div className="spread"><Spread/></div></section><footer><a className="button" href={page===37?"/book-next8?page=36&mode=student":`/book-next9?page=${page-1}&mode=student`}>← Предыдущий</a><span>{page} / 38</span><button disabled={page===38} onClick={()=>setPage(p=>Math.min(38,p+1))}>Следующий →</button></footer><style jsx global>{`
*{box-sizing:border-box}html,body{margin:0;background:#e9e5ed;color:#2b2432;font-family:Inter,Arial,sans-serif}main{min-height:100vh;padding-bottom:24px}header{height:72px;display:flex;align-items:center;gap:22px;padding:0 28px;background:#fff;border-bottom:1px solid #ded7e4;position:sticky;top:0;z-index:20}.brand{display:flex;align-items:center;gap:12px}.brand img{width:72px}.brand div{display:grid}.brand b{color:#5220a8}.brand span{font-size:12px;color:#8a8191}.meta{margin-left:auto;display:flex;gap:8px}.meta span{padding:8px 11px;border-radius:999px;background:#f1ecf7;color:#6130b5;font-size:13px;font-weight:800}.meta span:last-child{background:#ebf6ee;color:#35734b}header a{color:#5220a8;text-decoration:none;font-weight:800;font-size:13px}.frame{padding:18px 22px 10px}.spread{max-width:1420px;margin:auto;display:grid;grid-template-columns:1fr 1fr;filter:drop-shadow(0 24px 40px #2d203b28)}.page{min-height:850px;background:#fffdf8;padding:28px 32px 24px;position:relative;overflow:hidden}.left{border-radius:18px 0 0 18px;border-right:1px solid #ddd4e2}.right{border-radius:0 18px 18px 0;border-left:1px solid #efe9f2}.num{position:absolute;right:30px;top:22px;font:800 42px Georgia;color:#f05b37}.eyebrow{margin:0 0 7px;color:#7444c6;font-size:10px;font-weight:900;letter-spacing:.11em}.page h1{margin:0 0 10px;font:800 34px/1.08 Georgia;max-width:84%}.page h2{margin:13px 0 8px;font:800 20px Georgia}.page p{line-height:1.4}.field{display:grid;gap:6px;border:1px solid #cfc5bb;padding:8px 9px 6px;margin:7px 0;background:#fffefb}.field b{font:700 14px Georgia}.field textarea{width:100%;border:0;outline:0;resize:vertical;font:13px/1.6 Inter;background:repeating-linear-gradient(to bottom,transparent 0,transparent 23px,#ddd7cf 24px);min-height:42px;color:#2a2233}.checks,.choices{display:grid;gap:6px}.checks label,.choices label{display:flex;gap:8px;align-items:flex-start;padding:7px 8px;border:1px solid #ddd5cd;border-radius:8px;background:#fff;font-size:13px;line-height:1.35}.choices{grid-template-columns:repeat(auto-fit,minmax(145px,1fr))}.choices label.sel{border-color:#7650aa;background:#f4effb}footer{max-width:1420px;margin:12px auto 0;padding:0 22px;display:flex;justify-content:space-between;align-items:center}footer button,.button{border:0;border-radius:12px;padding:11px 15px;background:#5b27b1;color:#fff;font-weight:800;text-decoration:none}footer button:disabled{opacity:.35}footer span{font-weight:900;color:#5b27b1}@media(max-width:980px){header{padding:0 16px}.brand div,.meta{display:none}.frame{padding:12px}.spread{grid-template-columns:1fr}.page{min-height:auto;border-radius:14px!important;border:0!important}.right{margin-top:12px}}@media(max-width:650px){header{height:62px}.page{padding:22px 16px}.page h1{font-size:29px}footer button,.button{font-size:12px;padding:9px 10px}}
`}</style></main>}
