"use client";

import { FormEvent, useEffect, useState } from "react";

type Role = "student" | "teacher";
type PageData = Record<string, string | boolean | number>;
type PlannerStore = Record<number, PageData>;

const pageTitles: Record<number,string> = {
  1:"Моя экспедиция к идее",2:"Сканирование локации",3:"Моё состояние и впечатления",4:"Путевой лист: Никола-Ленивец",5:"Рефлексия экспедиции",
  6:"Штаб-квартира проекта",7:"Карта знаний и дефицитов",8:"Подготовка пилота",9:"Проект в работе",10:"Финальный план МАРСфеста",
  11:"Разбор полётов: Абхазия",12:"Абхазия: яркие открытия",13:"Финальный план пилота",14:"Команда пилота",15:"От МАРСфеста до Partners Day",
  16:"Питч перед партнёрами",17:"Подготовка к вопросам",18:"Карта состояний проектного цикла",19:"Команда и открытия",20:"Итоги проектного цикла"
};
const text=(d:PageData,k:string)=>String(d[k]??"");
const checked=(d:PageData,k:string)=>Boolean(d[k]);

function MarsLogo(){return <img className="marsLogo" src="/mars-logo.svg" alt="МАРС"/>}
function Field({label,value,readOnly,rows=2,onChange}:{label:string;value:string;readOnly:boolean;rows?:number;onChange:(v:string)=>void}){return <label className="field"><span>{label}</span><textarea rows={rows} value={value} readOnly={readOnly} onChange={e=>onChange(e.target.value)}/></label>}
function Check({label,value,readOnly,onChange}:{label:string;value:boolean;readOnly:boolean;onChange:(v:boolean)=>void}){return <label className="check"><input type="checkbox" checked={value} disabled={readOnly} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function RangeList({items,data,set,readOnly,prefix="state"}:{items:string[];data:PageData;set:any;readOnly:boolean;prefix?:string}){return <>{items.map((x,i)=><label className="range" key={x}><span>{x}</span><input type="range" min="1" max="10" value={Number(data[prefix+i]??5)} disabled={readOnly} onChange={e=>set(prefix+i,Number(e.target.value))}/><b>{Number(data[prefix+i]??5)}</b></label>)}</>}
function Generic({title,sections,data,set,readOnly}:{title:string;sections:{title:string;fields:string[]}[];data:PageData;set:any;readOnly:boolean}){return <div className="sheet twoCol">{sections.map((s,si)=><section key={s.title}><h2>{si===0?title:s.title}</h2>{s.fields.map((f,i)=><Field key={f} label={f} value={text(data,`s${si}f${i}`)} readOnly={readOnly} rows={i===0?4:3} onChange={v=>set(`s${si}f${i}`,v)}/>)}</section>)}</div>}

function PageOne(p:any){return <Generic {...p} title="Моя экспедиция к идее" sections={[{title:"Идея",fields:["Название проекта/идеи","Первая мысль или искра","Что мы сделали?","Что получилось?","Что не получилось?"]},{title:"Экипаж и роли",fields:["Моя основная роль","Кто в команде и какую суперсилу привнёс","Мне в этой роли было… потому что…","Хочу попробовать себя в роли"]}]}/>}
function PageTwo(p:any){return <Generic {...p} title="Сканирование локации" sections={[{title:"Проектная инициатива",fields:["Главный признак успеха","Как называется проект?","В чём его суть?","Для кого он?","Главная фишка/технология"]},{title:"Зона туманности",fields:["Вопросы без ответа","Какие эксперты или помощь нужны?","Главная сложность или риск","Заметки"]}]}/>}
function PageThree(p:any){return <Generic {...p} title="Моё состояние" sections={[{title:"Состояние",fields:["Настроение после интенсива","Сегодня я чувствую себя как…","Что радует в замысле?","Что вызывает беспокойство?"]},{title:"Список дел",fields:["Шаг 1","Шаг 2","Шаг 3","Заметки"]}]}/>}
function PageFour(p:any){return <Generic {...p} title="Путевой лист экспедиции" sections={[{title:"Моя роль и цель",fields:["Моя роль в походе","Главная цель","Что я хочу наблюдать?"]},{title:"Штурманская папка",fields:["Что должен увидеть","Другой объект","Снаряжение","Группа и тактика"]}]}/>}
function PageFive({data,set,readOnly}:any){return <div className="sheet twoCol"><section><h2>Карта состояния</h2><RangeList items={["Старт","Середина пути","Сложный участок","Привал","Финиш"]} {...{data,set,readOnly}}/><Field label="Что чувствовало тело?" value={text(data,"body")} readOnly={readOnly} rows={5} onChange={v=>set("body",v)}/><Field label="Моя роль в команде" value={text(data,"teamRole")} readOnly={readOnly} onChange={v=>set("teamRole",v)}/></section><section><h2>Самые яркие открытия</h2><Field label="Вид, который меня поразил" value={text(data,"view")} readOnly={readOnly} rows={7} onChange={v=>set("view",v)}/><Field label="Звук, который запомнился" value={text(data,"sound")} readOnly={readOnly} onChange={v=>set("sound",v)}/><Field label="Неожиданное наблюдение за собой" value={text(data,"observation")} readOnly={readOnly} rows={4} onChange={v=>set("observation",v)}/><Field label="Главный вывод" value={text(data,"conclusion")} readOnly={readOnly} rows={5} onChange={v=>set("conclusion",v)}/></section></div>}
function PageSix(p:any){return <Generic {...p} title="Статус проекта" sections={[{title:"Статус",fields:["Название проекта/инициативы","Моя роль","Этап проекта","Первый эксперт: имя, направление, главный совет","Второй эксперт: имя, направление, главный совет"]},{title:"Инсайт этапа",fields:["Самый ценный вопрос","Самый неожиданный ответ эксперта","Главное открытие о проекте","Следующий шаг","Заметки"]}]}/>}
function PageSeven(p:any){return <Generic {...p} title="Карта знаний и дефицитов" sections={[{title:"Что мы знаем и умеем",fields:["Знание/навык 1","Знание/навык 2","Знание/навык 3","Знание/навык 4"]},{title:"Чего не знаем и кто поможет",fields:["Дефициты","Нужные эксперты/партнёры","Главный вывод по карте","Заметки"]}]}/>}
function PageEight(p:any){return <Generic {...p} title="Подготовка пилота" sections={[{title:"Прототип",fields:["Название проекта","Что показываем завтра?","Роли команды"]},{title:"Обратная связь",fields:["Как собираем фидбек","Как поймём, что пилот удался?","Последние штрихи"]}]}/>}
function PageNine(p:any){return <Generic {...p} title="Проект в работе" sections={[{title:"Наблюдения",fields:["Что получилось сегодня","Что было непонятно детям","Самая важная цитата ребёнка","Что изменили в прототипе"]},{title:"Обработка обратной связи",fields:["Баги/неполадки","Непонятный интерфейс","Идеи нового функционала","Восторги — что сохранить","Решение команды"]}]}/>}
function PageTen(p:any){return <Generic {...p} title="Финальный план: МАРСфест завтра" sections={[{title:"Цель",fields:["Название проекта","Финальная цель пилота","Расписание на 5 дней"]},{title:"Контроль",fields:["Что делаем вместе с детьми","Что фиксируем/собираем","Главный риск и план Б"]}]}/>}

function PageEleven({data,set,readOnly}:any){return <div className="sheet twoCol"><section><h2>Экспедиционный отчёт: Абхазия</h2><Field label="Даты поездки" value={text(data,"dates")} readOnly={readOnly} onChange={v=>set("dates",v)}/><RangeList items={["Старт: сборы и отъезд","Поезд туда","Первые дни","Середина","Кульминация","Поезд обратно","Финиш"]} {...{data,set,readOnly}}/><h3>Физический и эмоциональный чек-лист</h3>{["Полное истощение, но удовлетворение","Бурная радость и лёгкость","Грусть, что всё закончилось","Спокойная усталость","Прилив сил и желание новых проектов"].map(x=><Check key={x} label={x} value={checked(data,x)} readOnly={readOnly} onChange={v=>set(x,v)}/>)}</section><section><h2>Ощущения и команда</h2><Field label="Самое сильное физическое ощущение" value={text(data,"physical")} readOnly={readOnly} rows={4} onChange={v=>set("physical",v)}/><Field label="Самое сильное эмоциональное переживание" value={text(data,"emotion")} readOnly={readOnly} rows={4} onChange={v=>set("emotion",v)}/><Field label="На что была похожа наша группа" value={text(data,"groupImage")} readOnly={readOnly} rows={4} onChange={v=>set("groupImage",v)}/><Field label="Моя роль в экспедиции" value={text(data,"role")} readOnly={readOnly} rows={4} onChange={v=>set("role",v)}/></section></div>}
function PageTwelve(p:any){return <Generic {...p} title="Самые яркие открытия" sections={[{title:"Впечатления",fields:["Вид, который врезался в память","Звук или запах, который буду помнить годами","Неожиданное наблюдение за собой","Главный вывод о себе как об исследователе и путешественнике"]},{title:"Связь опытов",fields:["Какая идея о проекте пришла во время поездки?","Какой навык из Абхазии поможет реализации проекта?","Заметки"]}]}/>}
function PageThirteen(p:any){return <Generic {...p} title="Финальный план пилота" sections={[{title:"Цель",fields:["Название проекта","Финальная цель пилота: что проверяем за 5 дней?","Расписание: понедельник","Расписание: вторник","Расписание: среда"]},{title:"Продолжение расписания",fields:["Расписание: четверг","Расписание: пятница","Что делаем вместе с детьми","Что фиксируем/собираем"]}]}/>}
function PageFourteen({data,set,readOnly}:any){return <div className="sheet twoCol"><section><h2>Проект в работе</h2><Field label="Финальная версия прототипа" value={text(data,"prototype")} readOnly={readOnly} rows={6} onChange={v=>set("prototype",v)}/><h3>Роли</h3>{["Ведущий-модератор","Наблюдатель-фиксатор","Технический специалист","Комьюнити-менеджер","Ответственный за тайминг"].map((x,i)=><Field key={x} label={x} value={text(data,"role"+i)} readOnly={readOnly} onChange={v=>set("role"+i,v)}/>)}</section><section><h2>Фидбек и готовность</h2>{["Материалы собраны","Прототип готов","Расписание согласовано","Роли распределены","План на завтра ясен каждому"].map(x=><Check key={x} label={x} value={checked(data,x)} readOnly={readOnly} onChange={v=>set(x,v)}/>)}<Field label="Как собираем фидбек" value={text(data,"feedback")} readOnly={readOnly} rows={5} onChange={v=>set("feedback",v)}/><Field label="Как поймём, что пилот удался?" value={text(data,"success")} readOnly={readOnly} rows={6} onChange={v=>set("success",v)}/><Field label="Что сделаем с обратной связью" value={text(data,"after")} readOnly={readOnly} rows={5} onChange={v=>set("after",v)}/></section></div>}
function PageFifteen(p:any){return <Generic {...p} title="Штурм проекта" sections={[{title:"Разбор полётов",fields:["Название проекта","Главная гипотеза","Подтвердилась ли она и почему?","Самая ценная обратная связь: что исправить","Что круто и стоит оставить","Количественные результаты"]},{title:"План технологизации",fields:["Какое решение мы приняли?","Список правок и доработок","Какие ресурсы и помощь экспертов нужны?","Карта оставшихся вопросов"]}]}/>}
function PageSixteen({data,set,readOnly}:any){return <div className="sheet twoCol"><section><h2>Питч перед партнёрами</h2><Field label="Наша цель на Partners Day" value={text(data,"goal")} readOnly={readOnly} rows={4} onChange={v=>set("goal",v)}/><Field label="Ключевое сообщение партнёрам" value={text(data,"message")} readOnly={readOnly} rows={4} onChange={v=>set("message",v)}/><Field label="Что показываем?" value={text(data,"format")} readOnly={readOnly} rows={4} onChange={v=>set("format",v)}/><Field label="Распределение ролей на питче" value={text(data,"roles")} readOnly={readOnly} rows={5} onChange={v=>set("roles",v)}/></section><section><h2>Структура питча</h2>{["Слайд 1. Проблема или возможность","Слайд 2. Решение","Слайд 3. Проверка гипотез","Слайд 4. Команда и план","Слайд 5. Призыв к действию"].map((x,i)=><Field key={x} label={x} value={text(data,"slide"+i)} readOnly={readOnly} rows={3} onChange={v=>set("slide"+i,v)}/>)}</section></div>}
function PageSeventeen({data,set,readOnly}:any){return <div className="sheet"><h2>Подготовка к вопросам: самое важное</h2><p>Сформулируйте собственные ответы и мосты к сильным сторонам проекта.</p>{[1,2,3,4,5].map(i=><div className="twoCol" key={i}><Field label={`Вопрос партнёра ${i}`} value={text(data,"q"+i)} readOnly={readOnly} rows={3} onChange={v=>set("q"+i,v)}/><Field label="Ваш ответ" value={text(data,"a"+i)} readOnly={readOnly} rows={4} onChange={v=>set("a"+i,v)}/></div>)}</div>}
function PageEighteen({data,set,readOnly}:any){return <div className="sheet twoCol"><section><h2>Карта состояний проектного цикла</h2><Field label="Название экспедиции" value={text(data,"name")} readOnly={readOnly} onChange={v=>set("name",v)}/><Field label="Даты МАРСфеста и Partners Day" value={text(data,"dates")} readOnly={readOnly} onChange={v=>set("dates",v)}/><RangeList items={["Старт","Середина МАРСфеста","Кульминация МАРСфеста","Подготовка к Partners Day","Partners Day","Финиш"]} {...{data,set,readOnly}}/></section><section><h2>После финиша</h2>{["Полное истощение, но удовлетворение","Бурная радость и лёгкость","Грусть, что интенсив закончился","Спокойная усталость","Прилив сил развивать проект дальше"].map(x=><Check key={x} label={x} value={checked(data,x)} readOnly={readOnly} onChange={v=>set(x,v)}/>)}<Field label="Самое сильное физическое ощущение" value={text(data,"physical")} readOnly={readOnly} rows={5} onChange={v=>set("physical",v)}/><Field label="Самое сильное эмоциональное переживание" value={text(data,"emotion")} readOnly={readOnly} rows={5} onChange={v=>set("emotion",v)}/></section></div>}
function PageNineteen(p:any){return <Generic {...p} title="Команда и открытия" sections={[{title:"Командная динамика",fields:["На что была похожа наша команда?","Моя роль в путешествии","Момент, который врезался в память","Самая ценная обратная связь"]},{title:"Связь опыта",fields:["Неожиданное наблюдение за собой","Главный вывод о себе как об авторе и презентаторе","Какой вопрос партнёров заставил задуматься?","Какой навык поможет дальше?"]}]}/>}
function PageTwenty({data,set,readOnly}:any){return <div className="sheet twoCol"><section><h2>Моя экспедиция к идее</h2><Field label="Название проекта" value={text(data,"project")} readOnly={readOnly} onChange={v=>set("project",v)}/><Field label="Кодовая фраза: суть идеи в одном предложении" value={text(data,"phrase")} readOnly={readOnly} rows={3} onChange={v=>set("phrase",v)}/><Field label="Как изменилась первая искра идеи?" value={text(data,"spark")} readOnly={readOnly} rows={5} onChange={v=>set("spark",v)}/><Field label="Итоговое видение проекта" value={text(data,"vision")} readOnly={readOnly} rows={7} onChange={v=>set("vision",v)}/><Field label="Что получилось?" value={text(data,"success")} readOnly={readOnly} rows={4} onChange={v=>set("success",v)}/><Field label="Что пока не получилось?" value={text(data,"failed")} readOnly={readOnly} rows={4} onChange={v=>set("failed",v)}/></section><section><h2>Экипаж и Partners Day</h2><Field label="Моя основная роль" value={text(data,"role")} readOnly={readOnly} rows={4} onChange={v=>set("role",v)}/><Field label="Мне в этой роли было… потому что…" value={text(data,"feeling")} readOnly={readOnly} rows={4} onChange={v=>set("feeling",v)}/><Field label="Хочу попробовать себя в роли" value={text(data,"nextRole")} readOnly={readOnly} onChange={v=>set("nextRole",v)}/><Field label="Как готовились и что презентовали на Partners Day" value={text(data,"partners")} readOnly={readOnly} rows={6} onChange={v=>set("partners",v)}/></section></div>}

const pages:any={1:PageOne,2:PageTwo,3:PageThree,4:PageFour,5:PageFive,6:PageSix,7:PageSeven,8:PageEight,9:PageNine,10:PageTen,11:PageEleven,12:PageTwelve,13:PageThirteen,14:PageFourteen,15:PageFifteen,16:PageSixteen,17:PageSeventeen,18:PageEighteen,19:PageNineteen,20:PageTwenty};

export default function Home(){
 const[role,setRole]=useState<Role|null>(null),[login,setLogin]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[page,setPage]=useState(1),[store,setStore]=useState<PlannerStore>({}),[saved,setSaved]=useState(false);
 useEffect(()=>{const raw=localStorage.getItem("mars-planner-v3");if(raw)try{setStore(JSON.parse(raw))}catch{}},[]);
 useEffect(()=>{if(!role)return;const t=setTimeout(()=>{localStorage.setItem("mars-planner-v3",JSON.stringify(store));setSaved(true);setTimeout(()=>setSaved(false),900)},450);return()=>clearTimeout(t)},[store,role]);
 function enter(e:FormEvent){e.preventDefault();setError("");if(login==="student"&&password==="1234")setRole("student");else if(login==="teacher"&&password==="1234")setRole("teacher");else setError("Проверьте логин и пароль")}
 function chooseDemo(next:Role){setLogin(next);setPassword("1234");setError("")}
 if(!role)return <main className="loginScreen"><div className="orbit orbitOne"/><div className="orbit orbitTwo"/><div className="planet planetOrange"/><div className="planet planetPurple"/><section className="loginIntro"><MarsLogo/><p className="loginEyebrow">ЦИФРОВАЯ ОБРАЗОВАТЕЛЬНАЯ СРЕДА</p><h1>Живая планёрка МАРС</h1><p className="loginTagline">Твой маршрут. Твои открытия. Твоё будущее.</p></section><section className="loginCard"><p className="loginWelcome">Добро пожаловать</p><h2>Вход в планёрку</h2><div className="roleSwitch"><button type="button" className={login==="student"?"selected":""} onClick={()=>chooseDemo("student")}>Я ученик</button><button type="button" className={login==="teacher"?"selected":""} onClick={()=>chooseDemo("teacher")}>Я педагог</button></div><form onSubmit={enter}><label>Логин<input value={login} onChange={e=>setLogin(e.target.value)}/></label><label>Пароль<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="loginButton">Войти</button></form></section></main>;
 const data=store[page]||{};const set=(key:string,value:any)=>setStore(s=>({...s,[page]:{...(s[page]||{}),[key]:value}}));const readOnly=role==="teacher";const P=pages[page];
 return <main className="appShell"><header><div><strong>МАРС</strong><span>Живая планёрка</span></div><nav><span>{role==="student"?"Ученик":"Педагог"}</span><button onClick={()=>setRole(null)}>Выйти</button></nav></header><div className="workspace"><aside><p className="eyebrow">СОДЕРЖАНИЕ</p><h2>Страницы 1–20</h2>{Object.entries(pageTitles).map(([n,t])=><button className={page===Number(n)?"active":""} key={n} onClick={()=>setPage(Number(n))}><span>{n}</span>{t}</button>)}</aside><section className="plannerPage"><div className="pageTop"><div><p className="eyebrow">СТРАНИЦА {page} ИЗ 38</p><h1>{pageTitles[page]}</h1></div><span className={saved?"save saved":"save"}>{saved?"Сохранено":"Автосохранение"}</span></div><P {...{data,set,readOnly}}/><section className="commentBox"><p className="eyebrow">КОММЕНТАРИЙ ПЕДАГОГА</p>{role==="teacher"?<textarea value={text(data,"teacherComment")} onChange={e=>set("teacherComment",e.target.value)} placeholder="Поддерживающий комментарий ученику…"/>:<p>{text(data,"teacherComment")||"Педагог пока не оставил комментарий."}</p>}</section></section></div></main>
}